### PR TITLE
changing the test

### PR DESCRIPTION
**Pull request by aechiara**
to test at the same line if result is Null or Empty

### CODE REVIEW

**Comment by zbateson** [comment]
Hi @aechiara --

Having the test for null separate from the test for "empty" is more explicit, and tests are better-written more explicitly, I know immediately if the issue is that it's "null" or "empty".  There's no point optimizing or being more concise in a test.

Also, calling another library should be avoided if possible in my opinion, whether ours or apache commons (although commons is *probably* more fine).  The reason being we don't want to test our "isEmptyString" in addition to the function be tested.  I'm also working on a v2 that won't include "isEmptyString", which is again a reason to not depend on anything external if/when possible -- they could be removed/altered, etc...  You can see the work being done at zbateson/DataDefender -- I should probably move it to a 2.0-dev branch here though or something so people can see that.

Thanks though for the contribution, I don't mean to discourage that generally, we definitely need more people involved :)

**Comment by aechiara** [comment]
> Hi @aechiara --
> 
> Having the test for null separate from the test for "empty" is more explicit, and tests are better-written more explicitly, I know immediately if the issue is that it's "null" or "empty". There's no point optimizing or being more concise in a test.
> 
> Also, calling another library should be avoided if possible in my opinion, whether ours or apache commons (although commons is _probably_ more fine). The reason being we don't want to test our "isEmptyString" in addition to the function be tested. I'm also working on a v2 that won't include "isEmptyString", which is again a reason to not depend on anything external if/when possible -- they could be removed/altered, etc... You can see the work being done at zbateson/DataDefender -- I should probably move it to a 2.0-dev branch here though or something so people can see that.
> 
> Thanks though for the contribution, I don't mean to discourage that generally, we definitely need more people involved :)

I understand, and thanks for the explication. I'd just made the PR, because the code was not building.
It is easy enough to break them apart again e test so i does not break, i'll do that now.

**Comment by zbateson** [comment]
Aah, thanks for that -- I see isBlank was introduced in Java 11, now I get it :)

**Comment by aechiara** [comment]
done

sorry for the trouble, i will follow the Contribute guidelines next time

cheers

**Pull request merged**
