### PR TITLE
fix an error trying to check if a string was blank by using .isBlank …

### PR DESCRIPTION
**Pull request by aechiara**
…direct on a string in side a unit test

### CODE REVIEW

**Comment by zbateson** [comment]
@aechiara 

The line before it is:

```
assertNotNull(rand);
```
Did the direct call to String.isBlank cause an issue for you anyway?

**Comment by aechiara** [comment]
> @aechiara
> 
> The line before it is:
> 
> ```
> assertNotNull(rand);
> ```
> 
> Did the direct call to String.isBlank cause an issue for you anyway?

No, it worked fine.

The version i cloned was 
```rand.isBlank()```

**Comment by zbateson** [comment]
Yeah, I'm refering to ``` rand.isBlank ``` also, but StringUtils.isBlank also checks for null, just wondering why you want to change the call to StringUtils if the line before rand.isBlank is already checking for null :)

**Comment by aechiara** [comment]
> Yeah, I'm refering to `rand.isBlank` also, but StringUtils.isBlank also checks for null, just wondering why you want to change the call to StringUtils if the line before rand.isBlank is already checking for null :)

i see your point, looking again to the code, it would be clear to change all the:

```
        assertNotNull(rand);
        assertFalse(StringUtils.isBlank(rand));
```

to

```
assertFalse(StringUtils.isBlank(rand));
```

would you agree ?

**Comment by aechiara** [comment]
i will close this one and create another PR

**Pull request closed without merging**
