### PR TITLE
check properties with command line argument properties file

### PR DESCRIPTION
**Pull request by aliwumi**
- add idea and eclipse project files to .gitignore
- check properties with command line argument properties file(not only the default db.properties)

### CODE REVIEW

**Comment by aliwumi** [comment]
Hi, armenak, thanks for approved my PR, but why does the PR unmerged?

**Comment by armenak** [comment]
Hello,

 

I do not know. On thing that came to my mind is that you closed and then re-opened the ticket. Please do the pull request again.

 

Armenak

**Comment by aliwumi** [comment]
Hi, armenak, I do the pr again[ 117](https://github.com/armenak/DataDefender/pull/117)

**Comment by armenak** [comment]
I approved the merge. Please let me know if you have any questions.

**Pull request closed without merging**
